#!/usr/bin/env sh

set -eu

docker compose -f compose/media/plex.yml config --quiet
docker compose -f compose/media/acquisition.yml config --quiet
docker compose -f compose/books/compose.yml config --quiet
